### ISSUE TITLE
Suggest A Change missing in deployed app

### ISSUE THREAD

**Issue by dopoto** [openpolitics/groupthink#373]
I've followed the set up instructions at https://github.com/openpolitics/groupthink/blob/master/README.md

My fork of https://github.com/openpolitics/template is here: https://github.com/dopoto/opt2
My Heroku app is here: https://opt-2b.herokuapp.com/

Once the app got deployed in Heroku, I was expecting to see the contents of https://github.com/dopoto/opt2/blob/master/index.md in https://opt-2b.herokuapp.com/ and the Suggest a Change button, but I only see the Proposals, Ideas and Contributors sections.

Is there any other set up step that I am missing?

**Comment by Floppy** [comment]
The "suggest a change" button is in the rendered Jekyll site at https://dopoto.github.io/opt2/ - that will send people to the heroku app to make the changes, vote, etc. I agree that that's far from clear though! It should link back to the actual text more obviously. Perhaps we should make the whole thing one site, rather than relying on github pages to render the actual resulting HTML from the document.
